name = "retell-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# CSV de orígenes para CORS
CORS_ORIGINS = "http://localhost:4000,https://fermaglo-widget.pages.dev"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "a05fab24739f4293b7b6f1b4bbde4032"
[observability.logs]
enabled = true